version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo-db'
    environment:
      - MONGO_INITDB_DATABASE=blogs
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=thisismyadminpassword
    volumes:
      - mongodb-volume:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb-volume:
